### ISSUE TITLE
Definir uma licença

### ISSUE THREAD

**Issue by augusto-herrmann** [belisards/coronabr#1]
Parabéns pelo trabalho de facilitar o acesso a esses dados que estavam "escondidos" dentro do arquivo javascript no [portal sobre o novo Coronavírus do Ministério da Saúde](http://plataforma.saude.gov.br/novocoronavirus/)! :clap: :clap: :clap: 

Para que os dados e o código sejam considerados abertos, entretanto, ainda é preciso definir uma **licença aberta**. Exemplos de possíveis licenças abertas para o código: GPLv3, MIT, etc. Exemplos de possíveis licenças abertas para os dados: CC-Zero, CC-BY 4.0, ODbL.

**Comment by belisards** [comment]
Bem lembrado! Coloquei lá. Se tiver sugestão de disponibilizar melhor esta informação, é só falar.

**Comment by augusto-herrmann** [comment]
Excelente! :+1:
