### ISSUE TITLE
Verificação dos dados 21-22-23 de acordo com Ministério da Saúde

### ISSUE THREAD

**Issue by ebettoni** [belisards/coronabr#10]
@belisards, dados verificados (mortes e confirmados, por UF) entre o repositório e os boletins oficiais:

- boletim 21/03 [Agência Saúde](https://www.saude.gov.br/noticias/agencia-saude/46571-coronavirus-18-mortes-e-1-128-casos-confirmados): **OK**
- boletim 22/03 [Agência Saúde](https://www.saude.gov.br/noticias/agencia-saude/46573-coronavirus-25-mortes-e-1-546-casos-confirmados): **OK**
- boletim 23/03 [Agência Saúde](https://www.saude.gov.br/noticias/agencia-saude/46589-coronavirus-34-mortes-e-1-891-casos-confirmados): **OK**

PS: Não localizei as notícias oficiais dos boletins 19 e 20.

**Comment by belisards** [comment]
Oi @ebettoni tem no repositório uma tabela com todos os links que usei como fontes para o preenchimento manual: https://github.com/belisards/coronabr/blob/master/dados/auxiliares/link_minsaude.csv

**Comment by ebettoni** [comment]
boletins 19/03 e 20/03 conferidos de acordo com o link do repositório: **OK**
