### ISSUE TITLE
Update 25-03-2019

### ISSUE THREAD

**Issue by ebettoni** [belisards/coronabr#11]
@belisards, mais uma vez parabéns pela agilidade e pelo trabalho.
Só uma alteração, sairam repetidas SC e RS. SC é 109 confirmados, 0 óbitos
```
42,"2020-03-25",,,,,,,123,,,0,"SC",,
43,"2020-03-25",,,,,,,123,,,1,"RS",,
```
Obrigado!

**Comment by belisards** [comment]
Eu que agradeço mais uma vez pela revisão e checagem, fundamental isso! Já está corrigido
