### ISSUE TITLE
Validação RS 27-03-2020

### ISSUE THREAD

**Issue by ebettoni** [belisards/coronabr#13]
@belisards , infelizmente não tem robô que dê conta dos erros que o próprio ministério comete (sad). a raspagem do teu robô na tabela está certinha, mas o próprio orgão vacilou na tabela.

Na tabela da [noticia](https://www.saude.gov.br/noticias/agencia-saude/46614-brasil-registra-3-417-casos-confirmados-de-coronavirus-e-92-mortes), ele apresentaram **RS** com `1` morte. 

Porém, no próprio corpo do texto, o valor é outro:

> as mortes estão localizadas nos estados do Amazonas (1), Ceará (3), Pernambuco (4), Rio de Janeiro (10), Goiás (1), Paraná (2), Santa Catarina (1) e Rio Grande do Sul (2).

É por isso que a tabela deles fechou com total `92`, mas a soma estado a estado (nível da raspagem), fechava `91`.

Procurei no site do RS pra me certificar, o dash deles fala em [duas mortes mesmo](http://ti.saude.rs.gov.br/covid19/).

Acho que vale corrigirmos se possível. Valeu

**Comment by belisards** [comment]
Excelente, @ebettoni ! Muito obrigado por notar a diferença. Os dados de óbitos por UF são cruciais agora pois nem a [plataforma oficial](https://covid.saude.gov.br/) está trazendo este detalhamento, só nos resta esta tabela mesmo..
