### ISSUE TITLE
dados/corona_brasil.csv não contém mortes antes de 29/03

### ISSUE THREAD

**Issue by cassianord** [belisards/coronabr#14]
Olá!
O título é auto explicativo. Antes a base corona_brasil.csv continha os dados diários de mortes, mas agora todas as mortes estão lançadas no último dia apenas, e os dias anteriores estão zerados. 

A propósito, deixo aqui o mais sincero agradecimento por disponibilizar esses dados. =)

**Comment by belisards** [comment]
Obrigada @cassianord ! 
Ontem separei as tabelas em duas para facilitar a compreensão e um erro no script estava zerando os dados de mortes do histórico.

Já está corrigido, obrigado por notar e vir aqui avisar!

Pode checar aí e qualquer coisa me avisa
