### ISSUE TITLE
MT se repete no dia 2020-03-30

### ISSUE THREAD

**Issue by patrickrmaia** [belisards/coronabr#15]
O estado do Mato Grosso se repete para as observações da data 2020-03-30. 

Aproveitando, muito obrigado pelo repo!

**Comment by belisards** [comment]
Obrigado @patrickrmaia ! Corrigido. Agora, recomendo utilizar daqui pra frente a série histórica oficial que finalmente foi ao ar em CSV: https://covid.saude.gov.br/
