### ISSUE TITLE
Empacotar dados como Data Package e colocar testes de validação automática no repositório

### ISSUE THREAD

**Issue by augusto-herrmann** [belisards/coronabr#4]
O padrão [Data Package](https://frictionlessdata.io/specs/data-package/) do [Frictionless Data](frictionlessdata.io/) possibilita automatizar a validação dos dados, validando-os automaticamente toda vez que alguma ação é realizada (ex.: push para o repositório no Github, criação de um *pull request*, etc.).

Pense nisto como uma [integração contínua para dados](http://okfnlabs.org/blog/2016/05/17/automated-data-validation.html), da mesma forma como normalmente se faz integração contínua para software.

**Comment by belisards** [comment]
Obrigado pelas contribuições, @augusto-herrmann !

Dei merge nos PRs, apenas voltei a data para o nome do arquivo CSV que você tinha renomeado para apenas coronabr

A princípio, espero que o próprio Ministério da Saúde em algum momento publique a série histórica de forma mais acessível. Porém, enquanto isso, pensei de automatizar a execução destes extrator com um servidor, para facilitar a geração de dashboards de análises, por exemplo. Ter essa validação automática é excelente!

**Comment by augusto-herrmann** [comment]
Disponha, @belisards !

A questão do nome do arquivo é que o `datapackage.json` precisa apontar para um nome de arquivo fixo, para que a validação funcione. Se o nome ficar mudando todo dia terá que ficar atualizando o `datapackage.json` também.

O histórico do arquivo já é mantido no próprio Git, por isso é sempre possível obter a versão anterior do arquivo, mesmo tendo um arquivo único no repositório. Se mesmo assim você acha importante ter vários arquivos, um com cada data, a minha sugestão é manter o mais atual sem a data no nome, e os antigos, arquivados, passarem a ser renomeados para nomes com data toda vez que surgir um arquivo novo.

**Comment by augusto-herrmann** [comment]
Em tempo, não quis deixar o badge visível no README?

**Comment by belisards** [comment]
Tem razão. Acho que podemos manter o mesmo arquivo. Sobre a badge do Goodtables, eu só movi mais para baixo. Sei que não é o padrão, mas achei que o ícone de "invalid data" solto, sem contexto, poderia acabar causando confusão.

**Comment by augusto-herrmann** [comment]
Certo. Vou trabalhar no código então para que os dados possam passar na validação.

**Comment by belisards** [comment]
Oi @augusto-herrmann você chegou a fazer esse código? Seria apenas para tirar os registros duplicados, certo?

Estou pensando em fazer outro script para deixar de atualizar manualmente e passar a extrair a tabela dos posts diários no blog do MS, a nova fonte dos dados federais.

**Comment by belisards** [comment]
Atualizei o script para remover os registros duplicados e agora está passando na validação: https://goodtables.io/github/belisards/coronabr/jobs/51
