### ISSUE TITLE
Arquivo 'corona_brasil.csv' só atualiza até 18/03.

### ISSUE THREAD

**Issue by rnwatanabe** [belisards/coronabr#6]

**Comment by augusto-herrmann** [comment]
O repositório apontado como alternativa supostamente atualizada ([jtrecenti/corona](https://github.com/jtrecenti/corona)) teve seu último commit há 2 dias. Ou seja, não está sendo atualizado também.

**Comment by belisards** [comment]
Oi, o objetivo principal do repositório é fornecer um script para extrair os dados. Não é uma API para acessar os dados, nem implementei nenhuma rotina para automatizar a publicação dos CSV. 

Fiz isso nos primeiros dias manualmente, mas posteriormente o @jtrecenti -  [(jtrecenti/corona)](https://github.com/jtrecenti/corona)  - fez um cron job para commitar lá o output CSV do script em R, então, linkei o repositório dele como dica para quem busca os dados.

O problema dos dados só atualizarem até 18/03 não é de nenhum dos scripts de extração. É da base disponibilizada pelo Ministério da Saúde. Reparem que não há a data 19/03/2020 no arquivo: [plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js](plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js)

**Comment by Mat-Bit** [comment]
Boa noite,
tentei extrair agora a base e depois de algumas tentativas sem sucesso vim aqui e para saber qual o problema e então realmente é por causa do site do governo que não ta constando mais o arquivo?

Vamos ver se tem alguma outra fonte ou mesmo que tenha que fazer um script para raspar os dados, para conseguir dar continuidade pra esse projeto

**Comment by belisards** [comment]
Oi @Mat-Bit você tem razão. O wget não está baixando o arquivo no script, vou ver aqui, talvez tenham mudado algo na configuração do servidor.

**Comment by belisards** [comment]
Na verdade, o arquivo [com a base do MS](https://plataforma.saude.gov.br/novocoronavirus/resources/scripts/database.js) está vazio no momento.

**Comment by Mat-Bit** [comment]
Sim, estava muito bom pra ser verdade o estado divulgar os dados de centralizados e de "alto nível".

Mas tem outro projeto semelhante que está em progresso, caso se estejam interessados, segue o link: https://github.com/turicas/covid19-br.git

**Comment by gstvribs** [comment]
Desde o dia 18, o site do ministério foi removido do ar e a base também, por causa disto os dados estão inconstantes, única base confiável que da pra trabalhar neste momento é o https://github.com/CSSEGISandData/COVID-19 que é base que a John Hopkings usa

**Comment by belisards** [comment]
Voltei a incluir a série histórica enquanto o site está fora do ar e estou arquivando os PPTs das coletivas de imprensa com os dados e tentando manter o CSV atualizado.
