### ISSUE TITLE
update dados do rio

### ISSUE THREAD

**Issue by ebettoni** [belisards/coronabr#8]
Olá! Parabéns pelo trabalho incrível.
Estou acompanhando a evolução pela sua compilação.
Hoje eles atualizaram os dados do Rio de Janeiro mais de uma vez. Confirmados foi para `305`. Fonte [Urk](https://www.saude.gov.br/noticias/agencia-saude/46593-coronavirus-46-mortes-e-2-201-casos-confirmados). Se puder atualizar ali na tabela.
Obrigado!

**Comment by belisards** [comment]
Oi @ebettoni obrigado pela notificação!  Vou atualizar já!
