### ISSUE TITLE
update dados Pará

### ISSUE THREAD

**Issue by ebettoni** [belisards/coronabr#9]
Olá, outro detalhe, pode ter sido dado corrigido a posteriori.
O Pará não tem nenhuma morte registrada até então, mas nos registros dos dias 21 e 22/3 ele aparece com duas mortes. Dá pra alterar para zero, como informa no site [21](https://www.saude.gov.br/noticias/agencia-saude/46571-coronavirus-18-mortes-e-1-128-casos-confirmados) e [22](https://www.saude.gov.br/noticias/agencia-saude/46573-coronavirus-25-mortes-e-1-546-casos-confirmados).
Obrigado!

**Comment by belisards** [comment]
Muito obrigado, @ebettoni ! Desde que o site saiu do ar, decidi fazer as atualizações manualmente, pois achei que seria uma instabilidade temporária.

Aproveitando aqui: faço sempre a atualização com cuidado e tento checar os números, mas pode ter passado algo errado. Se você (ou alguém mais) puder, seria muito legal revisar os números de mortes e confirmados para os estados, do dia 19 até hoje. Só para ter uma checagem dupla e garantir que está tudo batendo.

Como parece que o MS vai continuar disponibilizando os dados assim, estou pensando em fazer um novo script para automatizar esse processo de extrair as tabelas e atualizar a série histórica.

**Comment by ebettoni** [comment]
@belisards pode contar com meu apoio! Vou dar uma olhada na série de 19 até hoje. 

Sobre o script, acho que é isso mesmo, vamos ter que se adaptar pra conseguir manter minimamente um canal com a série histórica. Agora deram pra divulgar somente via boletim. 

Ontem ainda, o boletim apresentou uma falha básica de soma e o comunicado oficial saiu errado (mas, quando a isso, não podemos fazer milagre). O somatório dos estados do Nordeste [link-oficial](https://www.saude.gov.br/noticias/agencia-saude/46593-coronavirus-46-mortes-e-2-201-casos-confirmados) dão _354_ na tabela. Contudo, se somar estado por estado dá _352_ (aqui vai um grande facepalm)!

Se eu encontrar correção eu te aviso! Valeu!

**Comment by belisards** [comment]
Disseram que amanhã vai sair um painel novo na coletiva de hoje. Vejamos...

Seguimos conversando sobre a checagem na outra issue, vou fechar essa aqui
